### ISSUE TITLE
Proposal: add trigger to randomWalk in addition to interval

### ISSUE THREAD

**Issue by jacobheun** [libp2p/js-libp2p-kad-dht#100]
Currently `randomWalk`, when enabled, triggers on a given interval (current default of 5mins). When a node is starting, if it uses `randomWalk` as a peer discovery mechanism, it can take 5 minutes to crawl the dht for new peers. Assuming you launch your node and take no dht actions (as these should result in discovered peers), this can take a while to gain a meaningful number of peers and contribute to the network.

Adding a trigger could enable us to find peers more quickly, and leave the randomWalk interval higher. My thought is that without a trigger, it's more likely that the randomWalk interval will be reduced to help with initial discovery which feels wasteful in terms of queries to the dht. If I leverage another discover mechanism like `libp2p-bootstrap`, I could configure my trigger for something like `10s` and leave the randomWalk interval at the default 5mins. By 10s I should be connected to several of the bootstrap nodes. Performing the randomWalk should result in many discovered peers, which in turn will lead to more connected peers, especially with libp2p auto dial on. The more quickly we're able to "bootstrap" into a good portion of the network, we'll also reduce our dependency on the Bootstrap nodes, which is beneficial for their health as well.

cc: @alanshaw

**Comment by dirkmc** [comment]
I like this idea :+1:

Could you explain how the trigger mechansm would work? Is it a one-time event that causes random walk to start?

**Comment by jacobheun** [comment]
> Is it a one-time event that causes random walk to start?

Yes, I guess `delay` is a better term. Currently, when we start randomWalk it waits for the interval period to occur. If we change the randomWalk to **also** execute a walk as soon as it starts, we can use the `delay` to start the service. This way once the `delay` as occurred we'll immediately execute the walk, and then run it on `interval` after that.

So a randomWalk config of:
```json
enabled: true,
interval: 300e3,
delay: 10e3,
...
```

would execute a walk at `10s, 5min 10s, 10m 10s, ...,` once the dht has started.

**Comment by dirkmc** [comment]
Can we just start the DHT with `{ randomWalk: { enabled: false }}`, and then call `dht.randomWalk.start()` once we are connected to enough bootstrap nodes?

**Comment by jacobheun** [comment]
Potentially, but this gets complicated because we don't do any tagging of peers yet. As the number of discovery services grow we need to know which peers are Bootstrap nodes, or more generally, which peers have DHTs. We do have the support to check the protocols a peer is running, so we could check who has DHTs once we have a muxed connection to them.

We also have to determine what that threshold is. If I happen to only connect to 1 node, but the threshold is 3, I would never start the random walk.

It can get convoluted pretty quickly. The delay is a crude approach, but with a delay of 10s you should be reasonably certain you're connected to a decent number Bootstrap nodes. Worst case scenario, you have to wait an additional `interval` for walk to run again.

**Comment by jacobheun** [comment]
I created a branch to play around with this https://github.com/libp2p/js-libp2p-kad-dht/pull/101

**Comment by alanshaw** [comment]
A initial delay to first run sounds good to me 👍

**Comment by vasco-santos** [comment]
Also like the initial delay! Good proposal
