### ISSUE TITLE
async/await syntax

### ISSUE THREAD

**Issue by kumavis** [libp2p/js-libp2p-kad-dht#106]
hello/
happy to help incrementally refactor to async/await syntax
I think this would be valuable even if the external apis are still cb

let me know if its appropriate to start this. i would PR incremental pieces and aim for 0 change in behavior and a focus on more readable code.

**Comment by kumavis** [comment]
i see there is a standing but aging and significantly conflicting PR here https://github.com/libp2p/js-libp2p-kad-dht/pull/82

**Comment by dirkmc** [comment]
Yes, any changes should be made to that PR.

Thanks @kumavis
