### ISSUE TITLE
Docs 404

### ISSUE THREAD

**Issue by diasdavid** [libp2p/js-libp2p-kad-dht#11]
https://libp2p.github.io/js-libp2p-kad-dht

**Comment by dignifiedquire** [comment]
did you publish this module? they are uploaded only on publish

**Comment by diasdavid** [comment]
Yep, it is published. I've been installing it directly. What else could be the case?

**Comment by jozanza** [comment]
I'm curious about using this lib in the browser, and I've love to take a look at the docs. Any chance we could fix this 404?

**Comment by diasdavid** [comment]
Not 404 anymore https://libp2p.github.io/js-libp2p-kad-dht/
