### ISSUE TITLE
RandomWalk - no public api to enable at runtime

### ISSUE THREAD

**Issue by kumavis** [libp2p/js-libp2p-kad-dht#110]
it would be nice to be able to enable randomWalk at runtime

randomWalk currently relies on options passed in to DHT at init

running at runtime currently requires using internal apis

```js
node._dht.randomWalk._options.enabled = true
node._dht.randomWalk.start()
```

**Comment by vasco-santos** [comment]
After the latest changes of the `go-libp2p-kad-dht`, we intend to rewrite most of the this codebase once we have a spec from the go implementation. Once that is done, we will guarantee this will be get done.

**Comment by achingbrain** [comment]
Randomwalk has been removed in favour of [routing table refresh](https://github.com/libp2p/js-libp2p-kad-dht/pull/215) so this is no longer necessary.
