### ISSUE TITLE
randomWalk start/stop does not take callbacks

### ISSUE THREAD

**Issue by kumavis** [libp2p/js-libp2p-kad-dht#111]
`randomWalk.start()` and `randomWalk.stop()` should take callbacks
https://github.com/libp2p/js-libp2p-kad-dht/blob/master/src/random-walk.js#L41

https://github.com/libp2p/interface-peer-discovery#api

Edit: interface has been updated to use promises instead of callbacks

**Comment by kumavis** [comment]
`libp2p-webrtc-star` **does** implement this correctly
https://github.com/libp2p/js-libp2p-webrtc-star/blob/master/src/index.js#L46-L47

**Comment by vasco-santos** [comment]
Closing this in favour of #44 that should be addressed once we refactor the DHT with the new spec.
