### ISSUE TITLE
TypeError in Query.stop

### ISSUE THREAD

**Issue by kumavis** [libp2p/js-libp2p-kad-dht#113]
```
2272-node-3 /home/xyz/Development/mesh-testing/node_modules/libp2p-kad-dht/src/query/index.js:100
2272-node-3     this._log(`${this.run.errors.length} of ${this.run.peersSeen.size} peers errored (${this.run.errors.length / this.run.peersSeen.size * 100}% fail rate)`)
2272-node-3                                  ^
2272-node-3 
2272-node-3 TypeError: Cannot read property 'length' of undefined
2272-node-3     at Query.stop (/home/xyz/Development/mesh-testing/node_modules/libp2p-kad-dht/src/query/index.js:100:34)
2272-node-3     at timeout (/home/xyz/Development/mesh-testing/node_modules/libp2p-kad-dht/src/private.js:527:15)
2272-node-3     at Timeout.timeoutCallback [as _onTimeout] (/home/xyz/Development/mesh-testing/node_modules/async/timeout.js:74:13)
2272-node-3     at ontimeout (timers.js:436:11)
2272-node-3     at tryOnTimeout (timers.js:300:5)
2272-node-3     at listOnTimeout (timers.js:263:5)
2272-node-3     at Timer.processTimers (timers.js:223:10)
```

**Comment by kumavis** [comment]
Seems `query.run()` is exiting before creating the `query.run` object (also see #114)
https://github.com/libp2p/js-libp2p-kad-dht/blob/ddf80fed9ca7e8b1ec096f3160535aa3fdb45b50/src/query/index.js#L57-L60
and then the timeout happens and we call `query.stop()`
https://github.com/libp2p/js-libp2p-kad-dht/blob/ddf80fed9ca7e8b1ec096f3160535aa3fdb45b50/src/private.js#L527
and `query.stop()` internally expects a `query.run` object

**Comment by jacobheun** [comment]
> somehow a query is started before the query manager is started (needs investigation?)

This _should_ only happen if something like `findProviders` is called before the dht is started, or after it stopped. Do you know if the code you're running is doing any offline querying?

**Comment by kumavis** [comment]
@jacobheun i have a loop announcing provided content and it seems that it starts before the node starts

this didnt seem to cause any problems other than exposing this bug
