### ISSUE TITLE
Query - run is overwritten

### ISSUE THREAD

**Issue by kumavis** [libp2p/js-libp2p-kad-dht#114]
Query has a method called `run`. Query also assigns to `this.run` which would shadow the method. Is this a mistake or intentional? If its intentional its surprising and should be heavily commented.

https://github.com/libp2p/js-libp2p-kad-dht/blob/ddf80fed9ca7e8b1ec096f3160535aa3fdb45b50/src/query/index.js#L56-L67

**Comment by kumavis** [comment]
query.run is called at least [here](https://github.com/libp2p/js-libp2p-kad-dht/blob/ddf80fed9ca7e8b1ec096f3160535aa3fdb45b50/src/index.js#L379)

**Comment by kumavis** [comment]
cant wait for the Awesome Typescript Endeavour :wink:

**Comment by kumavis** [comment]
related https://github.com/libp2p/js-libp2p-kad-dht/issues/113

**Comment by vasco-santos** [comment]
This should be fixed by #116
