### ISSUE TITLE
Failed to provide to 1 of 20 peers

### ISSUE THREAD

**Issue by kumavis** [libp2p/js-libp2p-kad-dht#118]
I'm still investigating but almost all of my clients have encountered this error message. Maybe they are accidentally trying to provide to themselves? Will report if I learn more

![image](https://user-images.githubusercontent.com/1474978/57763022-2f2c9880-7733-11e9-89f8-60987b5d133e.png)

**Comment by jacobheun** [comment]
We probably should change this behavior so that it doesn't error and instead log the individual errors. Ideally we'd try peers until we have 20, but I think in the interim, providing to the majority of peers shouldn't return an error.

We do need to figure out the underlying cause if it's this consistent. If we're attempting to provide to peers, we should have already connected to them as part of the `getClosestPeers` query. The most likely things I can think of are:
1. There's a bug where we're not actually connecting to the peer on the `getClosestPeers` query.
2. There's a bug preventing us from reconnecting to the peer. Perhaps it was somehow blacklisted on disconnect.
3. The peer went offline / became undialable after we queried it and before we tried to provide.

**Comment by kumavis** [comment]
Saw one error:
```js
Error: stream ended with:0 but wanted:1
    at drain (index.js:43) pull-reader
    at index.js:63 pull-reader
    at index.js:20 pull-reader
    at onNext (index.js:15) pull-catch
    at drain (index.js:126) stream-to-pull-stream
    at Channel.<anonymous> (index.js:151) stream-to-pull-stream
    at emitOne (events.js:111)
    at Channel.emit (events.js:184)
    at Channel.emit (channel.js:96) libp2p-mplex
    at emitErrorNT (destroy.js:79) readable-stream
```

not super useful error message

**Comment by kumavis** [comment]
my transport is webrtc-star, so it may be that the connection dropped but it hasnt been recognized as down yet

**Comment by kumavis** [comment]
ok this time i was able to trace it up to the error source, its `simple-peer`
```js
self.destroy(makeError('Ice connection failed.', 'ERR_ICE_CONNECTION_FAILURE'))
```

So yeah, I agree, I wouldn't expect a single failure to error the whole process

As a tangent -- why isnt the error more meaningful?
`simple-peer` internally it seems to end the stream as is instead of propagating the error
```js
  if (!self._readableState.ended) self.push(null)
  if (!self._writableState.finished) self.end()
```

it does later emit an error
```js
if (err) self.emit('error', err)
```

**Comment by jacobheun** [comment]
> Error: stream ended with:0 but wanted:1

> As a tangent -- why isnt the error more meaningful?

We likely aren't handling stream ending properly, locally and/or remotely. That error message is likely a result of `pull-length-prefixed` attempting to decode a 0 length, unencoded message. It would try to read the non existent header and pull-reader would return that error.

@vasco-santos as we go through the new Connection/Stream interface updates we should really work on improving our testing around connection/stream ending.

**Comment by kumavis** [comment]
I'm not 100% on whether `simple-peer`'s behavior here is to blame or not but I filed this https://github.com/feross/simple-peer/issues/468 to get some clarification

**Comment by kumavis** [comment]
got another one:
```js
Error: No available transports to dial peer QmWvMivm1pECR8G98ZVS3k9B6EgGbqMbFwnsdkkEhVaeVq!
    at createError (index.js:4)
    at CONNECTION_FAILED (errors.js:6)
    at nextTransport (index.js:227)
    at index.js:240
    at transport.js:106
    at index.js:59
    at tryEach.js:78
    at once.js:12
    at replenish (eachOfLimit.js:61)
    at iterateeCallback (eachOfLimit.js:50)
```

**Comment by jacobheun** [comment]
If we were previously able to connect to that peer, which we presumably did during `getClosestPeers`, we somehow lost the ability to connect to it. My assumption is that we're losing connections to the relay nodes we previously connected through and our path to connecting to that peer no longer exists.

**Comment by kumavis** [comment]
yeah thats what i assumed, just want to report what im seeing

**Comment by kumavis** [comment]
seems like the error propagation is actually a bug in `stream-to-pull-stream`, as `pump` handles the error correctly https://github.com/kumavis/stream-to-pull-stream-bug

**Comment by kumavis** [comment]
actually my test is currently incorrect, due to poor error handling in `toPull.duplex()`

**Comment by kumavis** [comment]
so I know that `toPull.duplex()` has at least one error propagation bug and I see we're using it in `libp2p-webrtc-star`'s `incommingDial` fn

**Comment by jacobheun** [comment]
`libp2p-tcp` and the multiplexers (spdy, mplex) are also using it (except for [pull-mplex](https://github.com/libp2p/pull-mplex)). If there's a bug there, the multiplexers could be aggravating/contributing to it.

**Comment by kumavis** [comment]
error propagates correctly when `toPull.duplex` is the source. This test passes:
```js
  pull(
    toPull.duplex(source),
    toPull.sink(sink, (err) => {
      t.ok(err && err.message.includes('dingdong'), 'saw expected error')
      t.end()
    })
  )
```
from [here](https://github.com/kumavis/stream-to-pull-stream-bug/blob/80afddd25d47df7aab7b73b89152fa7abe3ec531/index.js#L44-L49)

However when the `pull.duplex()` receives an error, it **does not** propagate it. Theres a second optional cb `toPull.duplex(stream, cb)` and the error ends up there. The stream ends without error, and `pull.collect` here has no error. This test fails:
```js
  const transform = miss.through.obj((chunk, enc, cb) => cb(null, chunk))
  pull(
    pull.error(new Error('dingdong')),
    toPull.transform(transform),
    pull.collect((err, result) => {
      t.ok(err && err.message.includes('dingdong'), 'saw expected error')
      t.end()
    })
  )
```
from [here](https://github.com/kumavis/stream-to-pull-stream-bug/blob/80afddd25d47df7aab7b73b89152fa7abe3ec531/index.js#L92-L100)

This seems like the problem but I'm having trouble connecting the final dots.

**Comment by autonome** [comment]
@kumavis can you still reproduce w/ async/await contemporary versions of this?

**Comment by kumavis** [comment]
will reopen if i can
