### ISSUE TITLE
Cleanup legacy code

### ISSUE THREAD

**Issue by vasco-santos** [libp2p/js-libp2p-kad-dht#130]
Once the Awesome Endeavour: Async Iterators [ipfs/js-ipfs#1670](https://github.com/ipfs/js-ipfs/issues/1670) is achieved in this repo, we must leverage this breaking change (will need users' to upgrade their codebase) to also remove all that legacy code that we currently maintain.

- [ ] Remove `add-provider.js` fallback for assuming the originator [libp2p/js-libp2p-kad-dht#129](https://github.com/libp2p/js-libp2p-kad-dht/pull/129)
- [ ] Remove definetly `maxTimeout` option from `dht.get`, `dht.getMany` and `dht.findPeer`
- [ ] ...

cc @jacobheun @dirkmc

**Comment by JustMaier** [comment]
Is there a workaround for the meantime? Just rolling back to earlier versions of the datastore libraries?

**Comment by achingbrain** [comment]
There is no legacy code here, it's been refactored several times.
