### ISSUE TITLE
Compatibility with Mainline DHT

### ISSUE THREAD

**Issue by KrishnaPG** [libp2p/js-libp2p-kad-dht#149]
Is this compatible with Mainline DHT? Can this be used to connect to Bittorrent / WebTorrent clients and piggyback on them to discover other rpc-peers (that use `libp2p-kad-dht` for RPC)?

Since Mainline DHT is one of most populous DHT currently available, being able to use those nodes for quick peer discovery would be a major plus.

Wondering how to make this work with Mainline DHT. Any config spec or bootstrap nodes to point to specifically?

**Comment by cndolo** [comment]
Hi @KrishnaPG , did you follow up on this?

**Comment by vasco-santos** [comment]
Hey @KrishnaPG @cndolo 

Apologies for the late answer. This is compatible with any libp2p node running the DHT protocol. This way, `Bittorrent`/ `WebTorrent` would have to run a libp2p node to be able to exchange DHT messages over libp2p connections.

There was a discussion related to this in the past https://github.com/webtorrent/webtorrent/issues/288
