### ISSUE TITLE
Oversized messages dropped without warning

### ISSUE THREAD

**Issue by dirkmc** [libp2p/js-libp2p-kad-dht#154]
In [two](https://github.com/libp2p/js-libp2p-kad-dht/blob/eee2f618b9ecce397846e4b6348984a9a009e3b0/src/network.js#L193) [places](https://github.com/libp2p/js-libp2p-kad-dht/blob/c49fa92dfcb5cc2e181c9b4af79932d49896856a/src/rpc/index.js#L63) in the code we drop messages that are too large.

We should probably send an error response to the sender.

It may be worth creating a transformer similar to [it-length-prefixed](https://github.com/alanshaw/it-length-prefixed) to check message length.

**Comment by dirkmc** [comment]
@alanshaw following up on the question in the weekly sync - is it possible for an oversized message to reach js-libp2p-kad-dht? Or is this already taken care of by lower layers?

**Comment by jacobheun** [comment]
It's not, and the sizes don't match. Mplex restricts messages to 1MB, so it won't make it to the DHT. Additionally, `it-length-prefixed` has a default decode restriction of 4MB, so messages wouldn't make it even if the muxer allowed it.

The DHT [comment](https://github.com/libp2p/js-libp2p-kad-dht/blob/master/src/constants.js#L37) of 4MB is wrong, the constant of `2 << 22` is 8MB, not 4, but it will never get called anyway. We should be able to safely remove the check in the DHT as it's superfluous.

**Comment by vasco-santos** [comment]
It seems so! Thanks for your analysis.
 @dirkmc would you like to PR it?

**Comment by alanshaw** [comment]
In `it-mplex` an oversize incoming message will cause an [error to be thrown (and caught)](https://github.com/libp2p/js-libp2p-mplex/blob/master/src/mplex.js#L147) in the sink, which in turn will [abort _all_ the mplexed streams](https://github.com/libp2p/js-libp2p-mplex/blob/master/src/mplex.js#L175-L176) (sends a RESET message to the remote). The error will be [re-thrown on the source side](https://github.com/libp2p/js-libp2p-mplex/blob/master/src/mplex.js#L158) for the application to catch.

An oversive outgoing message will also cause an [error to be thrown](https://github.com/libp2p/js-libp2p-mplex/blob/master/src/mplex.js#L181) in the source, which in turn will [abort _all_ the mplexed streams](https://github.com/libp2p/js-libp2p-mplex/blob/master/src/mplex.js#L175-L176) (sends a RESET message to the remote).

I do not know if go-mplex deals with this - I don't remember seeing code that did...

**Comment by jacobheun** [comment]
> I do not know if go-mplex deals with this - I don't remember seeing code that did...

IIRC go-mplex will actually automatically split the messages into a maximum size, which we should eventually be doing for js-mplex. So it's not possible in go, when using mplex, to send an oversized message as it is automatically sliced for you.

**Comment by alanshaw** [comment]
Ok so, I was curious - go-mplex does throw at the top level https://github.com/libp2p/go-mplex/blob/8e818a96b0e2bbdc7bd825d3c8a2e131515e78ed/multiplex.go#L568 but the splitting _is done_ by the multiplexed streams on write:

https://github.com/libp2p/go-mplex/blob/8e818a96b0e2bbdc7bd825d3c8a2e131515e78ed/stream.go#L142-L159

**Comment by alanshaw** [comment]
https://github.com/libp2p/js-libp2p-mplex/pull/100
