### ISSUE TITLE
for-await handled serially

### ISSUE THREAD

**Issue by kumavis** [libp2p/js-libp2p-kad-dht#164]
https://github.com/libp2p/js-libp2p-kad-dht/commit/f0e68004b8c559c3214a1e0aaa94a15a26826085#diff-463b2787d6b1decd9b30c6a23ef7aa95

@vasco-santos 
If I'm understanding this correctly, with this new AsyncIterator and for-await syntax we:
- we start messaging our first dht peer sooner (yay!)
- message subsequent peers serially after awaiting a response (boo!)

Seems like we want to do the message sending in parallel, so we'd want some async parallel queue ( maybe https://github.com/dbushong/async-q#queue )

Does that make sense? Need a good general solution here, seems common to want to chain async actions originating from an AsyncIterator and handle them all in parallel

**Comment by vasco-santos** [comment]
@kumavis the first step here was to have an async iterable being returned from now. 

Internally, we are still not leveraging the real capabilities of `async iterators` for the majority of the cases yet. So you are right that the end goal is to handle that stuff in parallel as we get them within the `for await` loop. Now that we expose this API externally and release the async refactor we intend to come back to the DHT soon.

One of the things that I have in mind (short term) is that, as well as to be able to use `.get` in an async iterable fashion (might replace getMany, and the user can iterate while he wants).

Hopefully, I will be able to dedicate more time to the `dht` next year, as we also want to rethink some stuff and improve the DHT in the browser runtimes.

**Comment by kumavis** [comment]
Sounds good!
Looks like `paramap-it` solves exactly this problem.

https://github.com/alanshaw/paramap-it

**Comment by kumavis** [comment]
Ah, while `paramap-it` should help we shouldn't need it's order preservation.

**Comment by vasco-santos** [comment]
yeah, you can have a look at [it-awesome](https://github.com/alanshaw/it-awesome). It has a lot of great modules we can use with async iterators
