### ISSUE TITLE
Providers are not actually cleaning anything up

### ISSUE THREAD

**Issue by blakebyrnes** [libp2p/js-libp2p-kad-dht#167]
The providers functionality has a cleanup function, but when it runs, it never actually finds any provided files. I think this is because datastore-fs is expecting a glob format, and the constants variable: c.PROVIDERS_KEY_PREFIX is just a path.

It works if you simply add '**' after the prefix path:
`const query = this.datastore.query({ prefix: c.PROVIDERS_KEY_PREFIX + '**' })`

**Comment by vasco-santos** [comment]
Thanks for reporting this issue @blakebyrnes 

Would you be interested in adding a test which fails the clean up and/or fix the issue? It would be great to have this fixed

**Comment by blakebyrnes** [comment]
I just took a peek under the covers. I don't actually know what to do about this one. It looks like this should actually behave correctly in Memory Datastore, and possibly in Level Datastore too. It's the File Datastore that has issues, since it uses glob format. So what I proposed would actually break Memory and Level, but fix File... Is this a datastore-fs bug?

**Comment by achingbrain** [comment]
I believe this bug has been fixed, there's a [test](https://github.com/libp2p/js-libp2p-kad-dht/blob/master/test/providers.spec.ts#L86-L112) that adds some provider records, waits for them to expire, then asserts that it can no longer load those provider records.

Please re-open if you are still observing this problem.
