### ISSUE TITLE
Install step is not working

### ISSUE THREAD

**Issue by artiya4u** [libp2p/js-libp2p-kad-dht#17]
In readme file shown 

> npm i libp2p-dht

but it not working.
I can use
> npm i libp2p-kad-dht

Is it correct?
Using npm 5.3.0

**Comment by diasdavid** [comment]
@artiya4u thanks, fixed with https://github.com/libp2p/js-libp2p-kad-dht/commit/550c0d9c37b3a9fc92fa34677b97994af67ceef7
