### ISSUE TITLE
Timeout handling in random walk query

### ISSUE THREAD

**Issue by danielrempe-ut** [libp2p/js-libp2p-kad-dht#192]
I am using kad-dht with random walk enabled in a largely browser-based network, and as such, peers come and go very often. I found that peer discovery via the DHT stops working after a random walk once one peer has disconnected from the network.

I was able to trace this problem to some incorrect error handling in random-walk.js. The query times out whenever there are disconnected peers in the routing table (which is fine) but then at line 118 in method _walk:
           **if (err && err.code !== 'ETIMEDOUT') {**

The problem is that the timeout error in question, which is thrown from line 179 of peer-routing/index.js, does not have a value in err.code, since it is not using "throw errcode" like the other errors. The error is actually just a regular javascript Error object containing the string "TimeoutError".

After the _walk method throws this timeout error, peer discovery subsequently no longer works.

I verified that changing the above line to "if (err && err.toString().indexOf 'TimeoutError' < 0)" fixes my problem. I can tell you guys are in the process of overhauling this stuff anyway, so you may have a totally different way you want to approach this. That's why I didn't create a pull request or anything. Let me know if you want me to.

**Comment by vasco-santos** [comment]
Hello @danielrempe-ut 

Thanks for reporting this issue.
I would say that the ideal solution would be to change https://github.com/libp2p/js-libp2p-kad-dht/blob/master/src/peer-routing/index.js#L179 to throw the error using the `err-code` module. Would you like to add a PR to fix this? Ideally, you should have a test with this.

**Comment by danielrempe-ut** [comment]
Yes, I'll create a PR. I haven't created a test before, so I'll have to figure that out as I do this. I'll probably be able to submit a PR tomorrow sometime.
