### ISSUE TITLE
Some security findings

### ISSUE THREAD

**Issue by aileenscott-uleska** [libp2p/js-libp2p-kad-dht#196]
Hi folks,

I hope you don’t mind, we were testing out our security automation tool and ran it against your project.  A few issues came out that you may want to check out - we weren’t sure how to submit a PDF here, so we uploaded it to https://source-security.co.uk/de672649-5ebc-44bb-8ea8-2981200bbf32/ if you wanna check it out.

Any issues or feedback, just let us know.

Aileen

**Comment by vasco-santos** [comment]
@aileenscott-uleska thanks for reporting these. I checked the document and it seems that the 3 occurrences you mention are not vulnerabilities and are present in the tests.

Closing this for now, feel free to open if something updates
