### ISSUE TITLE
Configure browser distribution build

### ISSUE THREAD

**Issue by HexaField** [libp2p/js-libp2p-kad-dht#207]
Currently, the browser distribution is not set up.

Webpack is set up for the package, it should just be a matter of configuring the package.

https://unpkg.com/libp2p-kad-dht shows the unbundled code

**Comment by vasco-santos** [comment]
Good catch. This should now be fixed with #208 

New release
https://unpkg.com/libp2p-kad-dht@0.20.3/dist/index.min.js

**Comment by HexaField** [comment]
Confirmed working. Thanks!
