### ISSUE TITLE
Bootstrapping

### ISSUE THREAD

**Issue by achingbrain** [libp2p/js-libp2p-kad-dht#231]
1. Seed routing tables with pre generated peers
2. Connect to a DHT server and perform a Refresh

**Comment by achingbrain** [comment]
1. Is implemented by https://github.com/libp2p/js-libp2p-kad-dht/pull/215

**Comment by bertrandfalguiere** [comment]
Can this be closed?

Feel free to hide my comment if I'm mistaken.

**Comment by achingbrain** [comment]
Yes, we run the self-query on startup that performs the refresh.
