### ISSUE TITLE
Random Walk (previously Bootstrap) is not started by default, why?

### ISSUE THREAD

**Issue by diasdavid** [libp2p/js-libp2p-kad-dht#26]
@dignifiedquire do you happen to remember why you never auto start random-walk neither here on in js-libp2p?

**Comment by vasco-santos** [comment]
I have only now checked that this issue already existed. 

In the tests that I am currently implementing for `DHT Interop`, I cannot have peers getting to know each other until I start the random walk. In GO land, their random walk is started immediately.

I already created two PRs for enabling this [js-libp2p-kad-dht#42](https://github.com/libp2p/js-libp2p-kad-dht/pull/42) and [js-libp2p#251](https://github.com/libp2p/js-libp2p/pull/251).

@dignifiedquire do you have any feedback on this?

**Comment by diasdavid** [comment]
@vasco-santos you have to have in mind that when go-libp2p DHT was built, there was still no concept of libp2p and therefore Peer Routing and Content Routing. When designing libp2p we made those explicitly separate and that is why this module gets 3 badges https://github.com/libp2p/js-libp2p-kad-dht#peer-routing

**Comment by vasco-santos** [comment]
Ok, this makes sense to be started by its users, if they intend to (like in `js-libp2p`)! Thanks David 

I will close this issue for now.
