### ISSUE TITLE
Getting started?

### ISSUE THREAD

**Issue by thEpisode** [libp2p/js-libp2p-kad-dht#28]
Hi, this library looks so good, but you have any snippet to create nodes? I see your API but I don't know how to implement it. Could you guide me please?

**Comment by chris-asl** [comment]
_This seems to be resolved now._  

I believe that in order to create nodes you need to use this module in conjuction with the libp2p library. You can find such snippets in libp2p2 [examples](https://github.com/libp2p/js-libp2p/tree/master/examples).

**Comment by vasco-santos** [comment]
Thanks for you comment @chris-asl 

@thEpisode look also to issue #36 . I will close this one, as we have #36 for tracking a usage example. Meanwhile, if you still have problems, feel free to reach us again!

**Comment by thEpisode** [comment]
Thank you guys! you're awesome
