### ISSUE TITLE
README.md references dead URLs

### ISSUE THREAD

**Issue by zeim839** [libp2p/js-libp2p-kad-dht#324]
[README.md](https://github.com/libp2p/js-libp2p-kad-dht/blob/master/README.md): Github is not rendering the _Peer Routing_, _Content Routing_ and _Peer Discovery_ sections. Visiting the referenced URLs returns a `404: Not Found` error.

**Comment by achingbrain** [comment]
Great spot, thanks so much - would you like to open a PR that fixes the docs?

**Comment by zeim839** [comment]
Apologies, I should've done that in the first place but I hadn't looked for the updated image src. at the time. I'll submit a PR in a few hours, thanks for reaching out.
