### ISSUE TITLE
How to monitor new CIDs added on a node?

### ISSUE THREAD

**Issue by wong2** [libp2p/js-libp2p-kad-dht#349]
Is there an event to listen for newly added CIDs on a specific node?

**Comment by wong2** [comment]
I'd like to monitor new files to build index for search engine

**Comment by BigLep** [comment]
@wong2 : I believe this is a better topic to raise in discuss.ipfs.tech so hopefully others from the community can share.  You'll get a broader audience than core maintainers this particularly js-libp2p library.
