### ISSUE TITLE
Treat /dns4 addresses as public

### ISSUE THREAD

**Issue by joeltg** [libp2p/js-libp2p-kad-dht#377]
Right now, both `removePrivateAddresses` and `removePublicAddresses` in src/utils.ts remove all multiaddrs that aren't /ip4 or /ip6.

Is there any reason we couldn't leave /dns4 addresses as public? The situation I'm in is that I'm deploying some bootstrap nodes on fly.io, which gives me a predictable DNS name but a dynamically-allocated ipv4, so I'd like to announce on `/dns4/my-app-name.fly.dev/tcp/...`.

**Comment by mpetrunic** [comment]
Triage notes: It's something we need @achingbrain input on

**Comment by achingbrain** [comment]
This sounds like something that should be possible - would you like to submit a PR with a test?

**Comment by justin0mcateer** [comment]
I also ran into this issue, I describe my use case and provide a small working (but not complete) patch in #407
