### ISSUE TITLE
During a put call, if any node fails to put, the entire put fails

### ISSUE THREAD

**Issue by blakebyrnes** [libp2p/js-libp2p-kad-dht#68]
Have a scenario where if you get closest peers, and one peer cannot reply back with success, the entire put fails.  I think ideally, if X number of peers can be written to, this should succeed.

Examples of what a node might not be able to write to kad:
1) The KAD is not initialized on that node.  Ie, it's running a "light" node.  Solutions to this could include an earlier detection (maybe in identify) of the protocols that a given node supports - and then not adding them to the kad peer group if the node does not support /ipfs/kad/1.0.0
2) The node is no longer connected

I believe the simplest solution is to change the "each" in async handler to a "some" handler, and changing the variable name of cb to something different for the inner loop (just a best practice).

  ```
put (key, value, callback) {
    this._log('PutValue %b', key)

    waterfall([
      (cb) => utils.createPutRecord(key, value, cb),
      (rec, cb) => waterfall([
        (cb) => this._putLocal(key, rec, cb),
        (cb) => this.getClosestPeers(key, cb),
        (peers, cb) => **each**(peers, (peer, **cb**) => {
          this._putValueToPeer(key, rec, peer, **cb**)
        }, cb)
      ], cb)
    ], callback)
  }
```
@jacobheun @vasco-santos  I can create a pr if you agree with the approach.

**Comment by vasco-santos** [comment]
Hello @blakebyrnes and thanks for reaching out and sorry for the delay answering this! 

I agree that we should not fail if we are able to put to a good set of peers and failing one for instance. This way, I believe that the best option here is to have a parameter to set the minimum number of peers to have a successful put (not applicable if the number of closest peers is less than it).

What do you think? It would be great if you could create a PR with this.

**Comment by blakebyrnes** [comment]
Sounds good.  I've got an implementation of this going.  Are you ok with the param being called "minPutPeers"?  I'm looking into tests right now, and several tests around "put" are failing with the default of 1 put peer that I chose.  Do you think we should have the default be 0 if no minimum peers are provided?  It would keep the behavior the same as current, but I do think it's potentially unexpected that the system is ok with putting to no peers.

**Comment by jacobheun** [comment]
I'd recommend a generic option like `minPeers`, since it might be good to reuse that elsewhere in the future and the called function already declares the `put`.

I also recommend keeping the current behavior, default of 0. While this may be unexpected behavior it prevents this from being a breaking change. In the future we can then change the behavior to what we would expect.

**Comment by blakebyrnes** [comment]
I updated the PR to use your suggestion of option name.  I had already gone down the path of not changing existing behavior, so glad we agree on that.
