### ISSUE TITLE
Allow to set randomWalk parameter through config

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/js-libp2p-kad-dht#76]
Currently, the `randomWalk` discovery is started when the DHT module is started:

https://github.com/libp2p/js-libp2p-kad-dht/blob/b2a9fc5ab53db5a0105004e30af29fb24beaddfe/src/index.js#L136-L147

However, because no parameters are passed to `randomWalk.start()`, the random walk starts with the default parameters:

https://github.com/libp2p/js-libp2p-kad-dht/blob/b2a9fc5ab53db5a0105004e30af29fb24beaddfe/src/random-walk.js#L26-L34

I think those parameters should be exposed in the config as something like:

```js

dht: {
    kBucketSize: 20,
    randomWalk: {
       enabled: true // This could replace the current `enabledDiscovery` flag,
       queriesPerPeriod: 1,
       interval: 30000,
       timeout: 10000
    }
}
```

**Comment by a1300** [comment]
I second this. This is missing for me also.

**Comment by vasco-santos** [comment]
Totally agree with this! Thanks for opening the issue and propose a solution @thomaseizinger

**Comment by jhiesey** [comment]
Does the random walk logic really belong in the DHT at all? Ultimately running the random walk just calls `findPeer`, which is public.

**Comment by thomaseizinger** [comment]
Are you suggesting that the functionality of random walks should be extracted into its own library - using what provides the ability to `findPeer`?

I think it could make sense.
However, for the time being, it is included in this one but wasn't configurable from the outside, so I'd suggest that this is actually a different topic :)

**Comment by vasco-santos** [comment]
We may consider having the `randomWalk` in a separate module when we refactor the DHT. For now, I think this is ok, but we can create an issue for that. Meanwhile, I will close this one.

Thanks for your contributions!
