### ISSUE TITLE
calling provide can trigger Error: Dial is currently blacklisted for this peer

### ISSUE THREAD

**Issue by kumavis** [libp2p/js-libp2p-kad-dht#99]
`provide` sometimes results in an `Error: Dial is currently blacklisted for this peer`

**Comment by kumavis** [comment]
Error comes from calling `network.sendMessage` here https://github.com/libp2p/js-libp2p-kad-dht/blob/e137297f5e7bc17a37f914614af433d5650e0552/src/index.js#L549

**Comment by kumavis** [comment]
seems like this is related to doing:
```js
  // connect to all discovered nodes
  node.on('peer:discovery', (peer) => {
    // ignore failures
    node.dial(peer, (err) => {})
  })
```

and discovering yourself :upside_down_face:

**Comment by kumavis** [comment]
https://github.com/libp2p/js-libp2p-webrtc-star/issues/171

**Comment by mkg20001** [comment]
created a proposal for permanently fixing this issue https://github.com/libp2p/js-libp2p-switch/issues/331

**Comment by kumavis** [comment]
I guess this was a 2 part issue covered by:
- discovers self libp2p/js-libp2p-switch#331
- blacklisted peer breaks provide https://github.com/libp2p/js-libp2p-kad-dht/issues/105
